      # Codecov 설정
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  backend:
    paths:
      - backend/
    carryforward: true

ignore:
  - "**/test/**"
  - "**/config/**"
  - "**/*Config.java"
  - "**/*Application.java"
  - "**/dto/**"