import {StyleSheet, Platform} from 'react-native';
import {sp, hp, fp, wp, iconSize, touchSize} from '../utils/responsive';

export const getStyles = (isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? '#121212' : '#FAFAFA',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingTop: hp(20),
      paddingHorizontal: sp(24),
      paddingBottom: hp(100),
    },
    // 세그먼트 컨트롤 스타일
    segmentedControlWrapper: {
      alignItems: 'center',
      marginBottom: hp(24),
    },
    segmentedControl: {
      flexDirection: 'row',
      borderRadius: sp(14),
      padding: sp(4),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.08,
      shadowRadius: sp(8),
      elevation: 2,
    },
    segmentButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(12),
      paddingHorizontal: sp(20),
      borderRadius: sp(10),
    },
    segmentButtonActive: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(3)},
      shadowOpacity: 0.2,
      shadowRadius: sp(6),
      elevation: 4,
    },
    segmentButtonFirst: {
      marginRight: sp(2),
    },
    segmentButtonLast: {
      marginLeft: sp(2),
    },
    segmentButtonText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    segmentButtonTextActive: {
      fontWeight: '700',
    },
    // 집중 모드 뱃지
    concentrationBadgeWrapper: {
      alignItems: 'center',
      marginBottom: hp(24),
    },
    concentrationBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(12),
      paddingHorizontal: sp(20),
      borderRadius: sp(12),
      shadowColor: '#2196F3',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(8),
      elevation: 5,
    },
    concentrationBadgeText: {
      fontSize: fp(15),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    modeBadge: {
      paddingVertical: hp(10),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.15,
      shadowRadius: sp(4),
      elevation: 3,
    },
    modeBadgeText: {
      fontSize: fp(14),
      fontWeight: '700',
      color: '#FFFFFF',
    },
    mainModeIndicator: {
      paddingVertical: hp(14),
      paddingHorizontal: sp(24),
      borderRadius: sp(12),
      alignItems: 'center',
      alignSelf: 'center',
      marginBottom: hp(24),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.15,
      shadowRadius: sp(4),
      elevation: 3,
    },
    mainModeText: {
      fontSize: fp(15),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    fullscreenBtn: {
      position: 'absolute',
      top: 0,
      left: 0,
      zIndex: 10,
      padding: sp(12),
      borderRadius: sp(24),
      backgroundColor: isDark ? '#2A2A2A' : '#F0F0F0',
    },
    settingsBtn: {
      position: 'absolute',
      top: 0,
      right: 0,
      zIndex: 10,
      padding: sp(12),
      borderRadius: sp(24),
      backgroundColor: isDark ? '#2A2A2A' : '#F0F0F0',
    },
    title: {
      fontSize: fp(28),
      fontWeight: '700',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      letterSpacing: -0.5,
    },
    sessionCounter: {
      fontSize: fp(14),
      color: isDark ? '#999999' : '#757575',
      marginTop: hp(4),
      fontWeight: '500',
    },
    modeContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: hp(36),
      gap: sp(10),
      backgroundColor: isDark ? '#1E1E1E' : '#F5F5F5',
      borderRadius: sp(16),
      padding: sp(5),
    },
    modeTab: {
      flex: 1,
      paddingVertical: hp(12),
      paddingHorizontal: sp(14),
      borderRadius: sp(12),
      alignItems: 'center',
    },
    modeTabActive: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.15,
      shadowRadius: sp(6),
      elevation: 4,
    },
    modeTabText: {
      fontSize: fp(12),
      fontWeight: '600',
      color: isDark ? '#666666' : '#999999',
      letterSpacing: 0.2,
    },
    modeTabTextActive: {
      color: '#FFFFFF',
      fontWeight: '700',
    },
    cycleInfoContainer: {
      alignItems: 'center',
      marginBottom: hp(20),
      paddingVertical: hp(10),
      paddingHorizontal: sp(20),
      backgroundColor: isDark ? '#1E1E1E' : '#F5F5F5',
      borderRadius: sp(12),
      alignSelf: 'center',
    },
    cycleInfoText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    timerContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(40),
      position: 'relative',
    },
    timeLeftText: {
      fontSize: fp(48),
      fontWeight: '800',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      marginTop: hp(24),
      letterSpacing: -2,
      fontVariant: ['tabular-nums'],
      textAlign: 'center',
    },
    timerContent: {
      position: 'absolute',
      alignItems: 'center',
    },
    timerText: {
      fontSize: fp(56),
      fontWeight: 'bold',
      color: isDark ? '#FFFFFF' : '#333333',
      fontVariant: ['tabular-nums'],
    },
    modeLabel: {
      fontSize: fp(18),
      color: isDark ? '#AAAAAA' : '#666666',
      marginTop: hp(8),
    },
    modeSelectArea: {
      paddingHorizontal: sp(20),
      marginBottom: hp(20),
    },
    timerModeRow: {
      flexDirection: 'row',
      gap: sp(10),
    },
    concentrationStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      paddingVertical: hp(10),
      paddingHorizontal: sp(20),
      borderRadius: sp(20),
      gap: sp(8),
    },
    concentrationStatusText: {
      color: '#FFFFFF',
      fontSize: fp(15),
      fontWeight: '700',
    },
    timerModeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(12),
      borderRadius: sp(10),
      gap: sp(6),
    },
    timerModeButtonActive: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.15,
      shadowRadius: sp(4),
      elevation: 2,
    },
    timerModeText: {
      fontSize: fp(14),
      fontWeight: '600',
    },
    todayStatsCard: {
      marginHorizontal: sp(20),
      marginBottom: hp(20),
      borderRadius: sp(16),
      padding: sp(16),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.05,
      shadowRadius: sp(8),
      elevation: 2,
    },
    todayStatsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayStatItem: {
      flex: 1,
      alignItems: 'center',
      gap: sp(4),
    },
    todayStatValue: {
      fontSize: fp(20),
      fontWeight: '700',
      marginTop: hp(4),
    },
    todayStatLabel: {
      fontSize: fp(12),
      fontWeight: '500',
    },
    todayStatDivider: {
      width: 1,
      height: hp(40),
      marginHorizontal: sp(16),
    },
    controls: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: sp(14),
      marginBottom: hp(36),
      paddingHorizontal: sp(20),
    },
    button: {
      paddingVertical: hp(16),
      paddingHorizontal: sp(36),
      borderRadius: sp(14),
      minWidth: wp(140),
      alignItems: 'center',
    },
    primaryButton: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(3)},
      shadowOpacity: 0.2,
      shadowRadius: sp(8),
      elevation: 6,
    },
    secondaryButton: {
      backgroundColor: isDark ? '#2A2A2A' : '#EFEFEF',
      borderWidth: 0,
    },
    buttonText: {
      fontSize: fp(16),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    secondaryButtonText: {
      color: isDark ? '#AAAAAA' : '#666666',
    },
    stats: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      backgroundColor: isDark ? '#1E1E1E' : '#FFFFFF',
      borderRadius: sp(18),
      padding: sp(26),
      marginHorizontal: 0,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(1)},
      shadowOpacity: isDark ? 0.2 : 0.06,
      shadowRadius: sp(10),
      elevation: 3,
      borderWidth: 0,
    },
    statItem: {
      alignItems: 'center',
      flex: 1,
    },
    statValue: {
      fontSize: fp(28),
      fontWeight: '800',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      marginBottom: hp(8),
      letterSpacing: -0.8,
    },
    statLabel: {
      fontSize: fp(12),
      color: isDark ? '#999999' : '#888888',
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    statDivider: {
      width: 1,
      backgroundColor: isDark ? '#2A2A2A' : '#EFEFEF',
      marginHorizontal: sp(20),
    },
    bottomNav: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor: isDark ? '#1E1E1E' : '#FFFFFF',
      paddingVertical: hp(8),
      paddingBottom: hp(8),
      borderTopWidth: 1,
      borderTopColor: isDark ? '#2A2A2A' : '#F0F0F0',
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(-2)},
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: sp(8),
      elevation: 10,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      paddingVertical: hp(4),
    },
    navIcon: {
      fontSize: fp(26),
      marginBottom: hp(4),
      opacity: 0.4,
    },
    navIconActive: {
      opacity: 1,
    },
    navLabel: {
      fontSize: fp(11),
      color: isDark ? '#666666' : '#888888',
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    navLabelActive: {
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      fontWeight: '700',
    },
    fullscreenContainer: {
      flex: 1,
      backgroundColor: isDark ? '#121212' : '#FAFAFA',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    fullscreenContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: sp(40),
      gap: sp(40),
    },
    currentTimeSection: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    currentTimeText: {
      fontSize: fp(120),
      fontWeight: '800',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      letterSpacing: -6,
      marginBottom: hp(32),
    },
    currentDateText: {
      fontSize: fp(24),
      fontWeight: '600',
      color: isDark ? '#999999' : '#666666',
      marginBottom: hp(20),
      letterSpacing: 0.5,
    },
    fullscreenModeLabel: {
      backgroundColor: isDark ? '#2A2A2A' : '#F0F0F0',
      paddingHorizontal: sp(20),
      paddingVertical: hp(12),
      borderRadius: sp(28),
      marginBottom: hp(40),
      alignSelf: 'flex-start',
    },
    fullscreenModeLabelText: {
      fontSize: fp(15),
      fontWeight: '700',
      color: isDark ? '#AAAAAA' : '#666666',
      letterSpacing: 0.5,
    },
    exitFullscreenButton: {
      position: 'absolute',
      right: sp(32),
      width: touchSize(52),
      height: touchSize(52),
      borderRadius: sp(26),
      backgroundColor: isDark ? 'rgba(42, 42, 42, 0.9)' : 'rgba(240, 240, 240, 0.9)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(3)},
      shadowOpacity: 0.25,
      shadowRadius: sp(8),
      elevation: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)',
    },
    exitFullscreenText: {
      fontSize: fp(22),
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      fontWeight: '600',
    },
    rotateButton: {
      position: 'absolute',
      top: hp(32),
      width: touchSize(52),
      height: touchSize(52),
      borderRadius: sp(26),
      backgroundColor: isDark ? 'rgba(42, 42, 42, 0.9)' : 'rgba(240, 240, 240, 0.9)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(3)},
      shadowOpacity: 0.25,
      shadowRadius: sp(8),
      elevation: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)',
    },
    rotateButtonText: {
      fontSize: fp(24),
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      fontWeight: '600',
    },
    fullscreenTimerContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    fullscreenPlayButton: {
      position: 'absolute',
      bottom: hp(20),
      width: touchSize(64),
      height: touchSize(64),
      borderRadius: sp(32),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(6),
      elevation: 8,
    },
    fullscreenPlayButtonPortrait: {
      bottom: undefined,
      top: hp(340),
    },
    fullscreenPlayButtonLandscape: {
      width: touchSize(80),
      height: touchSize(80),
      borderRadius: sp(40),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(6)},
      shadowOpacity: 0.35,
      shadowRadius: sp(10),
      elevation: 12,
      marginTop: hp(8),
    },
    fullscreenPlayButtonText: {
      fontSize: fp(36),
      color: '#FFFFFF',
      fontWeight: '600',
    },
    fullscreenPlayButtonCenter: {
      position: 'absolute',
      width: touchSize(80),
      height: touchSize(80),
      borderRadius: sp(40),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(6)},
      shadowOpacity: 0.35,
      shadowRadius: sp(10),
      elevation: 12,
      zIndex: 10,
    },
    // 세로 모드 스타일
    fullscreenContentPortrait: {
      flexDirection: 'column',
      paddingHorizontal: sp(24),
      paddingTop: hp(40),
      paddingBottom: hp(40),
      justifyContent: 'flex-start',
      flex: 1,
    },
    currentTimeSectionPortrait: {
      alignItems: 'center',
      width: '100%',
      paddingTop: hp(30),
      paddingBottom: hp(10),
      marginBottom: hp(20),
    },
    currentTimeTextPortrait: {
      fontSize: fp(72),
      fontWeight: '800',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      letterSpacing: -4,
      marginBottom: hp(8),
    },
    currentDateTextPortrait: {
      fontSize: fp(16),
      fontWeight: '600',
      color: isDark ? '#999999' : '#666666',
      letterSpacing: 0.5,
    },
    fullscreenTimerContainerPortrait: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'flex-start',
      flex: 1,
      marginTop: hp(-20),
    },
    fullscreenPlayButtonBelowTimer: {
      width: touchSize(80),
      height: touchSize(80),
      borderRadius: sp(40),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(6)},
      shadowOpacity: 0.35,
      shadowRadius: sp(10),
      elevation: 12,
      marginTop: hp(40),
    },
    fullscreenTimeLeftText: {
      fontSize: fp(64),
      fontWeight: '800',
      marginTop: hp(20),
      letterSpacing: -3,
      fontVariant: ['tabular-nums'],
    },
    // Modal styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '85%',
      borderRadius: sp(20),
      padding: sp(24),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(10),
      elevation: 10,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(24),
    },
    modalTitle: {
      fontSize: fp(22),
      fontWeight: '700',
      letterSpacing: -0.5,
    },
    modalTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    timerHelpButton: {
      padding: sp(8),
    },
    timerHelpModalContent: {
      width: '90%',
      maxHeight: '80%',
      borderRadius: sp(20),
      padding: sp(20),
    },
    timerHelpModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(16),
    },
    timerHelpModalTitle: {
      fontSize: fp(20),
      fontWeight: '700',
    },
    timerHelpModalBody: {
      marginBottom: hp(16),
    },
    timerHelpCard: {
      padding: sp(16),
      borderRadius: sp(12),
      marginBottom: hp(12),
    },
    timerHelpIconRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(10),
      marginBottom: hp(8),
    },
    timerHelpEmoji: {
      fontSize: fp(24),
    },
    timerHelpCardTitle: {
      fontSize: fp(16),
      fontWeight: '700',
    },
    timerHelpCardText: {
      fontSize: fp(14),
      lineHeight: fp(22),
    },
    timerHelpCloseButton: {
      padding: sp(16),
      borderRadius: sp(12),
      alignItems: 'center',
    },
    timerHelpCloseButtonText: {
      color: '#FFFFFF',
      fontSize: fp(16),
      fontWeight: '700',
    },
    settingsInputContainer: {
      gap: hp(20),
      marginBottom: hp(24),
      maxHeight: hp(500),
    },
    settingGroup: {
      borderRadius: sp(12),
      padding: sp(16),
      marginBottom: hp(16),
    },
    settingGroupTitle: {
      fontSize: fp(16),
      fontWeight: '700',
      marginBottom: hp(12),
    },
    settingItemInGroup: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: hp(8),
    },
    settingDivider: {
      height: 1,
      marginVertical: hp(8),
    },
    settingItem: {
      gap: hp(8),
    },
    settingLabel: {
      fontSize: fp(15),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    settingInput: {
      padding: sp(16),
      borderRadius: sp(12),
      fontSize: fp(18),
      fontWeight: '600',
      textAlign: 'center',
    },
    appModeSelector: {
      flexDirection: 'row',
      gap: sp(10),
    },
    appModeButton: {
      flex: 1,
      paddingVertical: hp(14),
      paddingHorizontal: sp(16),
      borderRadius: sp(12),
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? '#3A3A3A' : '#E0E0E0',
    },
    appModeButtonActive: {
      borderColor: 'transparent',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.15,
      shadowRadius: sp(4),
      elevation: 3,
    },
    appModeButtonText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    appModeButtonTextActive: {
      fontWeight: '700',
    },
    currentModeIndicator: {
      paddingVertical: hp(12),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      alignItems: 'center',
      marginBottom: hp(8),
    },
    currentModeText: {
      fontSize: fp(13),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    settingsDivider: {
      height: 1,
      marginVertical: hp(16),
    },
    settingDescription: {
      fontSize: fp(12),
      marginTop: hp(4),
      marginBottom: hp(12),
      lineHeight: hp(18),
    },
    blockedTabsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
      marginTop: hp(8),
    },
    blockedTabButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(10),
      paddingHorizontal: sp(14),
      borderRadius: sp(10),
      borderWidth: 1.5,
      gap: sp(6),
    },
    blockedTabButtonText: {
      fontSize: fp(13),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    modalSaveButton: {
      paddingVertical: hp(16),
      borderRadius: sp(12),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.2,
      shadowRadius: sp(4),
      elevation: 4,
    },
    modalSaveButtonText: {
      fontSize: fp(17),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    // Lock Screen Styles
    lockScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: sp(24),
      paddingTop: Platform.OS === 'ios' ? hp(50) : hp(24),
      paddingBottom: hp(24),
    },
    lockContent: {
      alignItems: 'center',
      width: '100%',
    },
    lockIconContainer: {
      width: sp(120),
      height: sp(120),
      borderRadius: sp(60),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: hp(24),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(8),
      elevation: 8,
    },
    lockTitle: {
      fontSize: fp(28),
      fontWeight: '800',
      marginBottom: hp(12),
      letterSpacing: -0.5,
    },
    lockSubtitle: {
      fontSize: fp(15),
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: hp(22),
      marginBottom: hp(40),
    },
    lockTimerContainer: {
      alignItems: 'center',
      marginBottom: hp(32),
    },
    lockTimeText: {
      fontSize: fp(52),
      fontWeight: '800',
      marginTop: hp(24),
      letterSpacing: -3,
      fontVariant: ['tabular-nums'],
    },
    lockCycleInfo: {
      paddingVertical: hp(12),
      paddingHorizontal: sp(24),
      borderRadius: sp(12),
      marginBottom: hp(32),
    },
    lockCycleText: {
      fontSize: fp(15),
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    lockPauseButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(16),
      paddingHorizontal: sp(32),
      borderRadius: sp(16),
      marginTop: hp(32),
      gap: sp(8),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
    },
    lockPauseButtonText: {
      color: '#FFFFFF',
      fontSize: fp(17),
      fontWeight: '700',
    },
    lockUnlockButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
      paddingVertical: hp(14),
      paddingHorizontal: sp(24),
      borderRadius: sp(12),
      borderWidth: 1,
      marginTop: hp(20),
    },
    lockUnlockButtonText: {
      fontSize: fp(15),
      fontWeight: '600',
    },
    // Unlock Prompt Styles
    unlockPromptOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    unlockPromptContent: {
      width: '85%',
      borderRadius: sp(20),
      padding: sp(28),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(10),
      elevation: 10,
    },
    unlockPromptTitle: {
      fontSize: fp(22),
      fontWeight: '700',
      marginTop: hp(20),
      marginBottom: hp(12),
      letterSpacing: -0.5,
    },
    unlockPromptMessage: {
      fontSize: fp(15),
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: hp(22),
      marginBottom: hp(28),
    },
    unlockPromptButtons: {
      flexDirection: 'row',
      gap: sp(12),
      width: '100%',
    },
    unlockPromptButton: {
      flex: 1,
      paddingVertical: hp(14),
      borderRadius: sp(12),
      alignItems: 'center',
    },
    unlockCancelButton: {
      borderWidth: 1,
      borderColor: isDark ? '#3A3A3A' : '#E0E0E0',
    },
    unlockConfirmButton: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.2,
      shadowRadius: sp(4),
      elevation: 4,
    },
    unlockCancelButtonText: {
      fontSize: fp(16),
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    unlockConfirmButtonText: {
      fontSize: fp(16),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    // App Blocker Styles
    permissionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(12),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      gap: sp(8),
      marginTop: hp(8),
    },
    permissionButtonText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    permissionGranted: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(12),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      gap: sp(8),
      marginTop: hp(8),
    },
    permissionGrantedText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    selectAppsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(12),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      gap: sp(8),
      marginTop: hp(8),
    },
    selectAppsButtonText: {
      fontSize: fp(14),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    appSelectorContent: {
      width: '90%',
      height: '80%',
      borderRadius: sp(20),
      padding: sp(24),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.3,
      shadowRadius: sp(10),
      elevation: 10,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: sp(16),
    },
    loadingText: {
      fontSize: fp(14),
      fontWeight: '500',
    },
    appListContent: {
      paddingVertical: hp(8),
    },
    appItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: sp(14),
      borderRadius: sp(12),
    },
    appItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(12),
      flex: 1,
    },
    appItemInfo: {
      flex: 1,
      gap: hp(4),
    },
    appItemName: {
      fontSize: fp(15),
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    appItemPackage: {
      fontSize: fp(12),
      fontWeight: '400',
    },
    appSelectorDoneButton: {
      paddingVertical: hp(16),
      borderRadius: sp(12),
      alignItems: 'center',
      marginTop: hp(16),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.2,
      shadowRadius: sp(4),
      elevation: 4,
    },
    appSelectorDoneButtonText: {
      fontSize: fp(17),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    // 집중 완료 카드 (화면 잠금 후 돌아왔을 때)
    focusCompletedCard: {
      marginTop: hp(24),
      borderRadius: sp(16),
      padding: sp(16),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(4)},
      shadowOpacity: 0.2,
      shadowRadius: sp(8),
      elevation: 6,
    },
    focusCompletedContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    focusCompletedLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    focusCompletedEmoji: {
      fontSize: fp(32),
      marginRight: sp(12),
    },
    focusCompletedTextContainer: {
      flex: 1,
    },
    focusCompletedTitle: {
      fontSize: fp(18),
      fontWeight: '800',
      color: '#FFFFFF',
    },
    focusCompletedSubtitle: {
      fontSize: fp(13),
      fontWeight: '500',
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: hp(2),
    },
    // 화면 잠금 집중 안내 카드
    lockHintCard: {
      marginTop: hp(24),
      borderRadius: sp(16),
      padding: sp(16),
    },
    lockHintContent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    lockHintTextContainer: {
      flex: 1,
      marginLeft: sp(12),
    },
    lockHintTitle: {
      fontSize: fp(15),
      fontWeight: '700',
    },
    lockHintSubtitle: {
      fontSize: fp(12),
      marginTop: hp(2),
    },
    lockStudyTimeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: sp(6),
      marginTop: hp(12),
      paddingVertical: hp(8),
      paddingHorizontal: sp(12),
      borderRadius: sp(8),
    },
    lockStudyTimeText: {
      fontSize: fp(14),
      fontWeight: '600',
      color: '#FFFFFF',
    },
    // 집중 결과 모달 스타일
    focusResultOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    focusResultContent: {
      width: '85%',
      borderRadius: sp(24),
      padding: sp(32),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(8)},
      shadowOpacity: 0.3,
      shadowRadius: sp(16),
      elevation: 15,
    },
    focusResultEmoji: {
      fontSize: fp(64),
      marginBottom: hp(12),
    },
    focusResultTitle: {
      fontSize: fp(28),
      fontWeight: '800',
      letterSpacing: -0.5,
      marginBottom: hp(24),
    },
    focusResultTimeContainer: {
      width: '100%',
      paddingVertical: hp(24),
      paddingHorizontal: sp(20),
      borderRadius: sp(16),
      alignItems: 'center',
      marginBottom: hp(20),
    },
    focusResultTimeMain: {
      fontSize: fp(40),
      fontWeight: '800',
      letterSpacing: -1,
    },
    focusResultTimeSub: {
      fontSize: fp(18),
      fontWeight: '600',
      marginTop: hp(4),
    },
    focusResultTimeLabel: {
      fontSize: fp(14),
      fontWeight: '500',
      marginTop: hp(8),
    },
    focusResultMessage: {
      fontSize: fp(15),
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: hp(24),
      marginBottom: hp(28),
    },
    focusResultButton: {
      width: '100%',
      paddingVertical: hp(16),
      borderRadius: sp(14),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(3)},
      shadowOpacity: 0.2,
      shadowRadius: sp(6),
      elevation: 5,
    },
    focusResultButtonText: {
      fontSize: fp(17),
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    // 잠금 설정 모달 스타일
    lockSettingsContent: {
      width: '88%',
      maxWidth: sp(380),
      borderRadius: sp(20),
      padding: sp(24),
      alignItems: 'stretch',
    },
    lockSettingsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: sp(10),
      marginBottom: hp(8),
    },
    lockSettingsTitle: {
      fontSize: fp(22),
      fontWeight: '700',
    },
    lockSettingsDesc: {
      fontSize: fp(14),
      textAlign: 'center',
      marginBottom: hp(20),
    },
    lockSettingsOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: sp(16),
      borderRadius: sp(14),
      borderWidth: 2,
      marginBottom: hp(12),
    },
    lockSettingsOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(12),
    },
    lockSettingsOptionTitle: {
      fontSize: fp(15),
      fontWeight: '600',
    },
    lockSettingsOptionDesc: {
      fontSize: fp(12),
      marginTop: hp(2),
    },
    lockSettingsTabs: {
      marginBottom: hp(16),
    },
    lockSettingsSubtitle: {
      fontSize: fp(13),
      fontWeight: '600',
      marginBottom: hp(10),
    },
    lockSettingsTabsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
    },
    lockSettingsTabChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: sp(12),
      paddingVertical: hp(8),
      borderRadius: sp(20),
      borderWidth: 1.5,
      gap: sp(6),
    },
    lockSettingsTabChipText: {
      fontSize: fp(13),
      fontWeight: '600',
    },
    lockSettingsButtons: {
      flexDirection: 'row',
      gap: sp(12),
      marginTop: hp(8),
    },
    lockSettingsButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(14),
      borderRadius: sp(12),
      gap: sp(6),
    },
    lockSettingsCancelButton: {},
    lockSettingsCancelText: {
      fontSize: fp(15),
      fontWeight: '600',
    },
    lockSettingsStartText: {
      fontSize: fp(15),
      fontWeight: '700',
      color: '#FFFFFF',
    },
    // 세션 메모 모달 스타일
    memoIconContainer: {
      width: sp(64),
      height: sp(64),
      borderRadius: sp(32),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: hp(12),
    },
    memoSubtitle: {
      fontSize: fp(14),
      fontWeight: '500',
      textAlign: 'center',
      marginBottom: hp(20),
    },
    memoInput: {
      width: '100%',
      height: hp(100),
      borderRadius: sp(12),
      padding: sp(14),
      fontSize: fp(15),
      fontWeight: '500',
      borderWidth: 1,
    },
    memoCharCount: {
      fontSize: fp(12),
      alignSelf: 'flex-end',
      marginTop: hp(6),
      marginBottom: hp(20),
    },
    memoButtons: {
      flexDirection: 'row',
      gap: sp(12),
      width: '100%',
    },
    memoSkipButton: {
      flex: 1,
      paddingVertical: hp(14),
      borderRadius: sp(12),
      alignItems: 'center',
    },
    memoSkipButtonText: {
      fontSize: fp(15),
      fontWeight: '600',
    },
    memoSaveButton: {
      flex: 1,
      paddingVertical: hp(14),
      borderRadius: sp(12),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(2)},
      shadowOpacity: 0.2,
      shadowRadius: sp(4),
      elevation: 4,
    },
    memoSaveButtonText: {
      fontSize: fp(15),
      fontWeight: '700',
      color: '#FFFFFF',
    },
    // 알람 설정 스타일
    toggleButton: {
      width: sp(50),
      height: sp(30),
      borderRadius: sp(15),
      justifyContent: 'center',
      paddingHorizontal: sp(3),
    },
    toggleKnob: {
      width: sp(24),
      height: sp(24),
      borderRadius: sp(12),
      shadowColor: '#000',
      shadowOffset: {width: 0, height: sp(1)},
      shadowOpacity: 0.2,
      shadowRadius: sp(2),
      elevation: 2,
    },
    alarmSoundItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(14),
      paddingHorizontal: sp(16),
      borderRadius: sp(10),
      marginHorizontal: sp(8),
      marginVertical: hp(4),
    },
    alarmSoundName: {
      fontSize: fp(15),
      fontWeight: '600',
      marginBottom: hp(2),
    },
    alarmSoundDescription: {
      fontSize: fp(12),
    },
  });
